### ISSUE TITLE
MacOS 14.4.1

### ISSUE THREAD

**Issue by smh000809** [ahai-code/vfox-bun#1]
➜ vfox install bun@1.1.2
plugin [PreInstall] method error: no version number provided

**Comment by ahai-code** [comment]
Thanks for pointing this out, it seems to be a bug in the plugin, you can run the 
`vfox search bun` first and then install it, I'll fix the bug later!

**Comment by ahai-code** [comment]
@smh000809 The bug has been fixed and you can use it after running `vfox update bun` to update the plugin.

**Comment by smh000809** [comment]
> @smh000809该bug已修复，运行`vfox update bun`更新插件后即可使用。

yes
